name: CI & CD

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

env:
  docker_image_name: rbonghi/jetson_stats

# Reference
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

jobs:
  build:
    name: Test on python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 1
      matrix:
        python-version: [2.7, 3.8, 3.9]
        
    steps:
    - run: echo "Branch $GITHUB_REF"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Make group jetson_stats
        sudo groupadd jetson_stats
        # Install test dependencies
        sudo ./tests/develop.sh -s
        # Upgrade pip
        sudo -H python -m pip install --upgrade pip
        # Install tox
        sudo -H pip install tox
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Test with tox
      run: |
        sudo tox -e py${{ matrix.python-version }}

  docker:
    name: "Build Docker image develop"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    # https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.docker_image_name }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=ref,event=tag
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      if: github.actor != 'dependabot[bot]'
      uses: docker/login-action@v2.0.0 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3.1.1
      with:
        push: ${{ github.actor != 'dependabot[bot]' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/arm64

  deploy:
    name: Deploy on PIP
    # needs: [build, docs]
    needs: [build, docker]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo -H python -m pip install --upgrade pip
        sudo -H pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        sudo python setup.py sdist
        twine upload dist/*
